antigen_chain_ids:
  - A
batch_size: 1
condition_on_antigen: true
condition_on_light_chain: true
epitope_idxs_or_all: all
heavy_chain_id: C
independent_loss: true
light_chain_id: B
lmdesign_num_decoding_orders: 1
lmdesign_num_lm_seqs: 1
lmdesign_num_pmpnn_seqs: 1
lmdesign_output_logit_temperature: 0.5
lmdesign_pmpnn_logit_temperature: 0.5
num_batches: 1
predict_light_chain: false
random_seed: null
region_order:
  - hcdr1
  - hcdr2
  - hcdr3
regions:
  hcdr1:
    chain: heavy
    positions:
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
  hcdr2:
    chain: heavy
    positions:
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
  hcdr3:
    chain: heavy
    positions:
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
save_path: /workspaces/models/submodules/igdesign/test_data/5J13/output.csv
structure_path: /workspaces/models/submodules/igdesign/test_data/5J13/input_chai.pdb
